# Generated by Django 4.1.2 on 2022-10-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_fileupload'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['model'], name='backend_veh_model_407b37_idx'),
        ),
    ]
