# Generated by Django 4.1.2 on 2022-10-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_vehicle_backend_veh_model_407b37_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
